"use client"

import { useState } from "react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { Copy, Download, Github, Terminal } from "lucide-react"
import { trackDownload } from "@/lib/gtag"

interface ProjectData {
  projectName: string
  language: string
  framework: string
  description: string
  tools: string[]
}

interface EnvironmentPreviewProps {
  projectData: ProjectData
}

export default function EnvironmentPreview({ projectData }: EnvironmentPreviewProps) {
  const [copied, setCopied] = useState(false)

  const generateFileStructure = () => {
    const structure = [`${projectData.projectName}/`, "├── README.md", "├── .gitignore", "├── package.json"]

    if (projectData.tools.includes("docker")) {
      structure.push("├── Dockerfile", "├── docker-compose.yml")
    }

    if (projectData.tools.includes("github-actions")) {
      structure.push("├── .github/", "│   └── workflows/", "│       └── ci.yml")
    }

    if (projectData.language === "javascript" || projectData.language === "typescript") {
      structure.push("├── src/", "│   └── index." + (projectData.language === "typescript" ? "ts" : "js"))

      if (projectData.tools.includes("eslint")) {
        structure.push("├── .eslintrc.json")
      }

      if (projectData.tools.includes("prettier")) {
        structure.push("├── .prettierrc")
      }
    }

    structure.push("└── ...")
    return structure.join("\n")
  }

  const generatePackageJson = () => {
    const packageJson = {
      name: projectData.projectName,
      version: "1.0.0",
      description: projectData.description || "Generated by EnvSetup.dev",
      main: "src/index." + (projectData.language === "typescript" ? "ts" : "js"),
      scripts: {
        start: "node src/index.js",
        dev: "nodemon src/index." + (projectData.language === "typescript" ? "ts" : "js"),
        build: projectData.language === "typescript" ? "tsc" : 'echo "No build step needed"',
        test: projectData.tools.includes("jest") ? "jest" : 'echo "No tests specified"',
      },
      dependencies: {},
      devDependencies: {},
    }

    if (projectData.language === "typescript") {
      packageJson.devDependencies = {
        ...packageJson.devDependencies,
        typescript: "^5.0.0",
        "@types/node": "^20.0.0",
      }
    }

    if (projectData.tools.includes("eslint")) {
      packageJson.devDependencies = {
        ...packageJson.devDependencies,
        eslint: "^8.0.0",
      }
    }

    if (projectData.tools.includes("prettier")) {
      packageJson.devDependencies = {
        ...packageJson.devDependencies,
        prettier: "^3.0.0",
      }
    }

    if (projectData.tools.includes("jest")) {
      packageJson.devDependencies = {
        ...packageJson.devDependencies,
        jest: "^29.0.0",
      }
    }

    return JSON.stringify(packageJson, null, 2)
  }

  const copyToClipboard = async (text: string) => {
    await navigator.clipboard.writeText(text)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const handleDownload = (type: "zip" | "github" | "cli") => {
    trackDownload(type, `${projectData.language}-${projectData.framework || "basic"}`)

    // Simulate download/action
    if (type === "zip") {
      // In a real app, this would trigger a ZIP download
      console.log("Downloading ZIP...")
    } else if (type === "github") {
      // In a real app, this would create a GitHub repo
      console.log("Creating GitHub repository...")
    } else if (type === "cli") {
      // In a real app, this would show CLI instructions
      console.log("Showing CLI instructions...")
    }
  }

  return (
    <div className="space-y-8">
      {/* Project Overview */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center justify-between">
            {projectData.projectName}
            <div className="flex gap-2">
              <Badge variant="secondary">{projectData.language}</Badge>
              {projectData.framework && <Badge variant="outline">{projectData.framework}</Badge>}
            </div>
          </CardTitle>
          {projectData.description && <CardDescription>{projectData.description}</CardDescription>}
        </CardHeader>
        <CardContent>
          <div className="flex flex-wrap gap-2">
            {projectData.tools.map((tool) => (
              <Badge key={tool} variant="secondary" className="text-xs">
                {tool}
              </Badge>
            ))}
          </div>
        </CardContent>
      </Card>

      {/* Download Options */}
      <Card>
        <CardHeader>
          <CardTitle>Download Your Environment</CardTitle>
          <CardDescription>Choose how you'd like to get your development environment</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <Button onClick={() => handleDownload("zip")} className="h-auto p-4 flex flex-col items-center gap-2">
              <Download className="w-6 h-6" />
              <div className="text-center">
                <div className="font-semibold">Download ZIP</div>
                <div className="text-xs opacity-75">Get all files in a ZIP archive</div>
              </div>
            </Button>

            <Button
              onClick={() => handleDownload("github")}
              variant="outline"
              className="h-auto p-4 flex flex-col items-center gap-2"
            >
              <Github className="w-6 h-6" />
              <div className="text-center">
                <div className="font-semibold">Push to GitHub</div>
                <div className="text-xs opacity-75">Create a new repository</div>
              </div>
            </Button>

            <Button
              onClick={() => handleDownload("cli")}
              variant="outline"
              className="h-auto p-4 flex flex-col items-center gap-2"
            >
              <Terminal className="w-6 h-6" />
              <div className="text-center">
                <div className="font-semibold">Use CLI</div>
                <div className="text-xs opacity-75">Generate with our CLI tool</div>
              </div>
            </Button>
          </div>
        </CardContent>
      </Card>

      {/* File Preview */}
      <Card>
        <CardHeader>
          <CardTitle>File Structure & Configuration</CardTitle>
          <CardDescription>Preview of the files and structure that will be generated</CardDescription>
        </CardHeader>
        <CardContent>
          <Tabs defaultValue="structure" className="w-full">
            <TabsList className="grid w-full grid-cols-3">
              <TabsTrigger value="structure">File Structure</TabsTrigger>
              <TabsTrigger value="package">package.json</TabsTrigger>
              <TabsTrigger value="readme">README.md</TabsTrigger>
            </TabsList>

            <TabsContent value="structure" className="mt-4">
              <div className="relative">
                <pre className="bg-muted p-4 rounded-lg text-sm overflow-x-auto">
                  <code>{generateFileStructure()}</code>
                </pre>
                <Button
                  size="sm"
                  variant="outline"
                  className="absolute top-2 right-2 bg-transparent"
                  onClick={() => copyToClipboard(generateFileStructure())}
                >
                  <Copy className="w-4 h-4" />
                  {copied ? "Copied!" : "Copy"}
                </Button>
              </div>
            </TabsContent>

            <TabsContent value="package" className="mt-4">
              <div className="relative">
                <pre className="bg-muted p-4 rounded-lg text-sm overflow-x-auto">
                  <code>{generatePackageJson()}</code>
                </pre>
                <Button
                  size="sm"
                  variant="outline"
                  className="absolute top-2 right-2 bg-transparent"
                  onClick={() => copyToClipboard(generatePackageJson())}
                >
                  <Copy className="w-4 h-4" />
                  {copied ? "Copied!" : "Copy"}
                </Button>
              </div>
            </TabsContent>

            <TabsContent value="readme" className="mt-4">
              <div className="relative">
                <pre className="bg-muted p-4 rounded-lg text-sm overflow-x-auto">
                  <code>{`# ${projectData.projectName}

${projectData.description || "Generated by EnvSetup.dev"}

## Getting Started

1. Install dependencies:
   \`\`\`bash
   npm install
   \`\`\`

2. Start development server:
   \`\`\`bash
   npm run dev
   \`\`\`

## Project Structure

- \`src/\` - Source code
- \`README.md\` - This file
- \`package.json\` - Project configuration

## Technologies Used

- ${projectData.language.charAt(0).toUpperCase() + projectData.language.slice(1)}${projectData.framework ? `\n- ${projectData.framework}` : ""}${projectData.tools.length > 0 ? `\n- ${projectData.tools.join("\n- ")}` : ""}

Generated with ❤️ by [EnvSetup.dev](https://envsetup.dev)`}</code>
                </pre>
                <Button
                  size="sm"
                  variant="outline"
                  className="absolute top-2 right-2 bg-transparent"
                  onClick={() =>
                    copyToClipboard(
                      `# ${projectData.projectName}\n\n${projectData.description || "Generated by EnvSetup.dev"}`,
                    )
                  }
                >
                  <Copy className="w-4 h-4" />
                  {copied ? "Copied!" : "Copy"}
                </Button>
              </div>
            </TabsContent>
          </Tabs>
        </CardContent>
      </Card>
    </div>
  )
}
