import { NextResponse } from "next/server"
import { getToken } from "next-auth/jwt"
import {
  generateDockerCompose,
  generateDockerfile,
  generateEnvExample,
  generateGitignore,
  generateReadme,
  generateToolFiles,
  type EnvironmentConfig,
} from "@/lib/deployment-config"

// Creates a real GitHub repository under the signed-in user's account and
// pushes the same files the ZIP download produces - same generator
// functions, same tools.includes("docker")/"git" gating as
// app/api/generate-deployment/route.ts, so "Push to GitHub" can never
// produce a different result than "Download ZIP" for the same config.
//
// Needs the `repo` OAuth scope, which lib/next-auth-options.ts requests at
// sign-in. A session created before that scope was added won't have it -
// GitHub's API returns 403/404 in that case, which we turn into a
// sign-out-and-back-in message rather than a raw API error.
export async function POST(req: Request) {
  const token = await getToken({ req: req as any })

  if (!token?.accessToken) {
    return NextResponse.json(
      { error: "Sign in with GitHub first." },
      { status: 401 },
    )
  }

  let body: { repoName?: string; isPrivate?: boolean; config?: EnvironmentConfig }
  try {
    body = await req.json()
  } catch {
    return NextResponse.json({ error: "Invalid request body." }, { status: 400 })
  }

  const { repoName, isPrivate, config } = body

  if (!repoName || !/^[a-zA-Z0-9._-]{1,100}$/.test(repoName)) {
    return NextResponse.json(
      { error: "Repository name can only contain letters, numbers, dots, hyphens, and underscores." },
      { status: 400 },
    )
  }
  if (!config || !config.language) {
    return NextResponse.json({ error: "Missing environment config." }, { status: 400 })
  }

  const ghHeaders = {
    Authorization: `Bearer ${token.accessToken}`,
    Accept: "application/vnd.github+json",
    "X-GitHub-Api-Version": "2022-11-28",
  }

  // 1. Create the repo. auto_init:true gives it an initial commit/README so
  // there's already a default branch to add files onto via the Contents API
  // below - creating a brand new empty repo's first commit would otherwise
  // need the lower-level Git Data API (create blob -> tree -> commit -> ref),
  // which is a lot more moving parts for the same end result.
  const createRes = await fetch("https://api.github.com/user/repos", {
    method: "POST",
    headers: { ...ghHeaders, "Content-Type": "application/json" },
    body: JSON.stringify({
      name: repoName,
      private: Boolean(isPrivate),
      description: config.description?.slice(0, 350) || `${config.projectName} — generated by EnvSetup.dev`,
      auto_init: true,
    }),
  })

  if (!createRes.ok) {
    const errBody = await createRes.json().catch(() => ({}) as { message?: string })
    if (createRes.status === 422) {
      return NextResponse.json(
        { error: `A repository named "${repoName}" already exists on your GitHub account. Pick a different name.` },
        { status: 422 },
      )
    }
    if (createRes.status === 401 || createRes.status === 403) {
      return NextResponse.json(
        { error: "GitHub rejected the request. Your sign-in may predate repo access being requested — sign out and sign back in with GitHub, then try again." },
        { status: 403 },
      )
    }
    return NextResponse.json(
      { error: errBody.message || "Failed to create the GitHub repository." },
      { status: createRes.status },
    )
  }

  const repo = await createRes.json()
  const repoFullName: string = repo.full_name

  // 2. Build the exact same file set the ZIP download produces.
  const tools = config.tools ?? []
  const files: Record<string, string> = {}
  if (tools.includes("docker")) {
    files["Dockerfile"] = generateDockerfile(config)
    files["docker-compose.yml"] = generateDockerCompose(config)
  }
  files[".env.example"] = generateEnvExample(config)
  files["README.md"] = generateReadme(config)
  for (const [path, content] of Object.entries(generateToolFiles(config))) {
    files[path] = content
  }
  if (tools.includes("git")) {
    files[".gitignore"] = generateGitignore()
  }

  // 3. Push each file with the Contents API. These are independent PUTs
  // (not a single atomic commit), so a partial failure is possible - we
  // report which paths failed rather than pretending an all-or-nothing
  // transaction happened.
  const failed: string[] = []
  for (const [path, content] of Object.entries(files)) {
    const putRes = await fetch(
      `https://api.github.com/repos/${repoFullName}/contents/${encodeURIComponent(path)}`,
      {
        method: "PUT",
        headers: { ...ghHeaders, "Content-Type": "application/json" },
        body: JSON.stringify({
          message: `Add ${path}`,
          content: Buffer.from(content, "utf-8").toString("base64"),
        }),
      },
    )
    if (!putRes.ok) failed.push(path)
  }

  return NextResponse.json({
    url: repo.html_url,
    fullName: repoFullName,
    filesWritten: Object.keys(files).length - failed.length,
    filesFailed: failed,
  })
}
