import { NextResponse, type NextRequest } from "next/server"
import { getToken } from "next-auth/jwt"
import {
  generateDockerCompose,
  generateDockerfile,
  generateEnvExample,
  generateGitignore,
  generateReadme,
  generateToolFiles,
  type EnvironmentConfig,
} from "@/lib/deployment-config"

// Creates a real GitHub repository under the signed-in user's account and
// pushes the same files the ZIP download produces - same generator
// functions, same tools.includes("docker")/"git" gating as
// app/api/generate-deployment/route.ts, so "Push to GitHub" can never
// produce a different result than "Download ZIP" for the same config.
//
// Needs the `repo` OAuth scope, requested inline by components/
// github-push-dialog.tsx only when someone actually opens this dialog (see
// that file's REPO_SCOPE) rather than at general sign-in. A token that
// predates that consent, or was already revoked (see revokeAccessToken
// below), won't have repo access - GitHub's API returns 401/403 in that
// case, which we turn into a REAUTH_REQUIRED code the dialog uses to offer
// one-click reconnect instead of a raw API error.
export async function POST(req: NextRequest) {
  const token = await getToken({ req })

  if (!token?.accessToken) {
    // Most likely cause: no repo-scoped grant yet - either this is the first
    // time this user has opened this dialog, or their last token was
    // revoked after a previous use (see revokeAccessToken) and this is a
    // fresh visit. Being "signed in" (status === "authenticated" client-side)
    // doesn't mean the token actually has repo access - say so explicitly
    // instead of a bare "sign in first", which reads as wrong to someone
    // already signed in.
    return NextResponse.json(
      {
        error: "Your GitHub sign-in doesn't have repository access yet. Sign out and sign back in with GitHub to grant it.",
        code: "REAUTH_REQUIRED",
      },
      { status: 401 },
    )
  }

  let body: { repoName?: string; isPrivate?: boolean; config?: EnvironmentConfig }
  try {
    body = await req.json()
  } catch {
    return NextResponse.json({ error: "Invalid request body." }, { status: 400 })
  }

  const { repoName, isPrivate, config } = body

  if (!repoName || !/^[a-zA-Z0-9._-]{1,100}$/.test(repoName)) {
    return NextResponse.json(
      { error: "Repository name can only contain letters, numbers, dots, hyphens, and underscores." },
      { status: 400 },
    )
  }
  if (!config || !config.language) {
    return NextResponse.json({ error: "Missing environment config." }, { status: 400 })
  }

  const accessToken = token.accessToken
  const ghHeaders = {
    Authorization: `Bearer ${accessToken}`,
    Accept: "application/vnd.github+json",
    "X-GitHub-Api-Version": "2022-11-28",
  }

  // Everything below actually uses the repo-scoped token, so no matter which
  // path this takes - success, GitHub rejecting the request, a name clash -
  // the finally block below revokes it before the response goes out. Repo
  // access only needs to exist for the few seconds this request runs, not
  // indefinitely between visits: revoking immediately after use means the
  // token can't sit around as standing access, and the next time this
  // person uses Push to GitHub, GitHub asks them to grant it again. That's
  // one extra consent screen per use in exchange for the app never holding
  // onto repo access it isn't actively using - the trade we want here.
  try {
    // 1. Create the repo. auto_init:true gives it an initial commit/README
    // so there's already a default branch to add files onto via the
    // Contents API below - creating a brand new empty repo's first commit
    // would otherwise need the lower-level Git Data API (create blob ->
    // tree -> commit -> ref), which is a lot more moving parts for the same
    // end result.
    const createRes = await fetch("https://api.github.com/user/repos", {
      method: "POST",
      headers: { ...ghHeaders, "Content-Type": "application/json" },
      body: JSON.stringify({
        name: repoName,
        private: Boolean(isPrivate),
        description: config.description?.slice(0, 350) || `${config.projectName} — generated by EnvSetup.dev`,
        auto_init: true,
      }),
    })

    if (!createRes.ok) {
      const errBody = await createRes.json().catch(() => ({}) as { message?: string })
      if (createRes.status === 422) {
        return NextResponse.json(
          { error: `A repository named "${repoName}" already exists on your GitHub account. Pick a different name.` },
          { status: 422 },
        )
      }
      if (createRes.status === 401 || createRes.status === 403) {
        return NextResponse.json(
          {
            error: "GitHub rejected the request. Your sign-in may predate repo access being requested — sign out and sign back in with GitHub, then try again.",
            code: "REAUTH_REQUIRED",
          },
          { status: 403 },
        )
      }
      return NextResponse.json(
        { error: errBody.message || "Failed to create the GitHub repository." },
        { status: createRes.status },
      )
    }

    const repo = await createRes.json()
    const repoFullName: string = repo.full_name

    // 2. Build the exact same file set the ZIP download produces.
    const tools = config.tools ?? []
    const files: Record<string, string> = {}
    if (tools.includes("docker")) {
      files["Dockerfile"] = generateDockerfile(config)
      files["docker-compose.yml"] = generateDockerCompose(config)
    }
    files[".env.example"] = generateEnvExample(config)
    files["README.md"] = generateReadme(config)
    for (const [path, content] of Object.entries(generateToolFiles(config))) {
      files[path] = content
    }
    if (tools.includes("git")) {
      files[".gitignore"] = generateGitignore()
    }

    // 3. Push each file with the Contents API. These are independent PUTs
    // (not a single atomic commit), so a partial failure is possible - we
    // report which paths failed rather than pretending an all-or-nothing
    // transaction happened.
    //
    // auto_init:true above already commits a README.md (GitHub always
    // creates one when initializing a repo this way) - the Contents API
    // rejects a PUT for a path that already exists unless the request
    // includes that file's current `sha`, otherwise it 422s with "sha
    // wasn't supplied". README.md was the one file that reliably failed
    // here because it's the one path guaranteed to already exist; every
    // other generated file used to get lucky by not colliding with
    // anything auto_init created. Checking for an existing sha first (and
    // sending it as an update when found) makes every path safe, not just
    // README.md, in case that ever changes.
    const failed: string[] = []
    for (const [path, content] of Object.entries(files)) {
      let sha: string | undefined
      const existingRes = await fetch(
        `https://api.github.com/repos/${repoFullName}/contents/${encodeURIComponent(path)}`,
        { headers: ghHeaders },
      )
      if (existingRes.ok) {
        const existing = await existingRes.json().catch(() => null as { sha?: string } | null)
        sha = existing?.sha
      }

      const putRes = await fetch(
        `https://api.github.com/repos/${repoFullName}/contents/${encodeURIComponent(path)}`,
        {
          method: "PUT",
          headers: { ...ghHeaders, "Content-Type": "application/json" },
          body: JSON.stringify({
            message: sha ? `Update ${path}` : `Add ${path}`,
            content: Buffer.from(content, "utf-8").toString("base64"),
            ...(sha ? { sha } : {}),
          }),
        },
      )
      if (!putRes.ok) failed.push(path)
    }

    return NextResponse.json({
      url: repo.html_url,
      fullName: repoFullName,
      filesWritten: Object.keys(files).length - failed.length,
      filesFailed: failed,
    })
  } finally {
    await revokeAccessToken(accessToken)
  }
}

// Immediately invalidates one specific GitHub access token via the OAuth
// App's token-revocation endpoint. This only kills *this* token - it does
// not sign the user out of EnvSetup or affect /history: their NextAuth
// session identity (login, email) lives in the JWT independent of whether
// this GitHub access token is still valid, since nothing else on the site
// calls the GitHub API with it. Best-effort: if the revoke call itself
// fails (GitHub hiccup, network blip), we don't fail the whole request over
// cleanup not completing - the token would just outlive this one use, same
// as before this existed, not a regression.
async function revokeAccessToken(accessToken: string) {
  const clientId = process.env.GITHUB_CLIENT_ID
  const clientSecret = process.env.GITHUB_CLIENT_SECRET
  if (!clientId || !clientSecret) return

  const basicAuth = Buffer.from(`${clientId}:${clientSecret}`).toString("base64")
  try {
    await fetch(`https://api.github.com/applications/${clientId}/token`, {
      method: "DELETE",
      headers: {
        Authorization: `Basic ${basicAuth}`,
        Accept: "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ access_token: accessToken }),
    })
  } catch {
    // Network failure talking to GitHub - nothing to do but let the token
    // age out naturally; the request above already got its real response.
  }
}
